version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cashcard
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
      
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: matias@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
      
  sonarqube:
  
     container_name: sonarqube 
     image: sonarqube:9.9.1-community
     ports:
      - "9000:9000"

networks:
  postgres:
    driver: bridge
    
volumes:
    postgres:
    pgadmin: